= Why AsciiDoc and Antora

In April 2021, I was looking for an alternative to conventional help authoring tools.
I had spent the last six years managing a team that used Help + Manual.
This was tool that I inherited on joining the company but I grew to like it, and I think that we managed to get a lot out of it.
However, it did not really fit well with online and specifically API documentation.

During an interview, a candidate had mentioned reStructuredText and Sphinx.
I began to investigate it and got quite far with it.
I fact i was considering recommending it to a company I was consulting to.
Fortunately in early May I stumbled across AsciiDoc.
Almost immediately I far preferred working with AsciiDoc.
The following are my subjective reasons:

Tables::
reStructuredText supports a number of ways of creating tables.
The most flexible, grid tables, is also the most frustrating because it relies on the author creating a text table using `+`, `-`, `|` and `=`:

[source,text]
----
+------------------------+------------+----------+----------+
| Header row, column 1   | Header 2   | Header 3 | Header 4 |
| (header rows optional) |            |          |          |
+========================+============+==========+==========+
| body row 1, column 1   | column 2   | column 3 | column 4 |
+------------------------+------------+----------+----------+
| body row 2             | ...        | ...      |          |
+------------------------+------------+----------+----------+
----

Alsthough such tables have the advnatage that they are easy to read in the source format, they are very inconvenient maintain.
In the time that I was using RST, I spent ages creating and modifying tables.
I really doubted that I could recommend this to technical writers who would be using tables extensively.

I should mention that there are alternatives for simple grid-like tables but they are quite restrictive.

By contrast, Asciidoc's principal table format is simple and flexible:

[source]
----
|===
|Header cell A |Header cell B |Header cell C

|Row 1A
|Row 1B
|Row 1C

|Row 2A
|Row 2B
|Row 2C

|===
----

Results in this:

|===
|Header cell A |Header cell B |Header cell C

|Row 1A
|Row 1B
|Row 1C

|Row 2A
|Row 2B
|Row 2C

|===

The source doesn't look much like a table but it's much easier to work with.
It's also possible to place all cells in a row on one line but this is not recommended except for the simplest tables.

Virtually anything can be included in a table:

[cols="3a,2"]
|===
| Column A |Column B

|
* List item 1
* List item 2
** Sublist item a
** Sublist item b
* List item 3
|Lists

|
[source,java]
----
class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
----
|Code blocks (and any other kind block)

|
!===
!Column A ! Column B !Column C

!Row 1A
!Row 1B
!Row 1C

!Row 2A
!Row 2B
!Row 2C

!===
|Even another table

|===

The table above is the result of this markup:

[source,asciidoc]
----
[cols="3a,2"]
|===
| Column A |Column B

|
* List item 1
* List item 2
** Sublist item a
** Sublist item b
* List item 3
|Lists

|
[source,java]
-----
class HelloWorld {
public static void main(String[] args) {
System.out.println("Hello, World!");
}
}
-----
|Code blocks (and any other kind block)

|
!===
!Column A ! Column B !Column C

!Row 1A
!Row 1B
!Row 1C

!Row 2A
!Row 2B
!Row 2C

!===
|Even another table

|===
----







